#!/bin/bash
echo "🔍 Pour voir les logs Vercel détaillés :"
echo ""
echo "Option 1 : Via le Dashboard"
echo "  1. Allez sur https://vercel.com/dashboard"
echo "  2. Cliquez sur votre projet 'flight-deals-phi'"
echo "  3. Allez dans 'Deployments'"
echo "  4. Cliquez sur le dernier déploiement"
echo "  5. Cliquez sur 'View Function Logs'"
echo "  6. Cherchez l'erreur de /api/auth/signup"
echo ""
echo "Option 2 : Via CLI"
echo "  vercel logs --follow"
echo ""
