// Base de données complète des aéroports mondiaux
// Source: Données IATA/ICAO standard

export interface Airport {
  code: string // Code IATA (3 lettres)
  name: string
  city: string
  country: string
  continent: string
  timezone: string
  coordinates: {
    lat: number
    lng: number
  }
}

// Liste complète des principaux aéroports mondiaux (500+)
// Organisée par volume de trafic et destinations populaires
export const AIRPORTS: Airport[] = [
  // Europe - Principaux hubs
  { code: 'CDG', name: 'Charles de Gaulle', city: 'Paris', country: 'France', continent: 'Europe', timezone: 'Europe/Paris', coordinates: { lat: 49.0097, lng: 2.5479 } },
  { code: 'ORY', name: 'Orly', city: 'Paris', country: 'France', continent: 'Europe', timezone: 'Europe/Paris', coordinates: { lat: 48.7233, lng: 2.3794 } },
  { code: 'LHR', name: 'Heathrow', city: 'Londres', country: 'Royaume-Uni', continent: 'Europe', timezone: 'Europe/London', coordinates: { lat: 51.4700, lng: -0.4543 } },
  { code: 'LGW', name: 'Gatwick', city: 'Londres', country: 'Royaume-Uni', continent: 'Europe', timezone: 'Europe/London', coordinates: { lat: 51.1537, lng: -0.1821 } },
  { code: 'STN', name: 'Stansted', city: 'Londres', country: 'Royaume-Uni', continent: 'Europe', timezone: 'Europe/London', coordinates: { lat: 51.8850, lng: 0.2350 } },
  { code: 'FCO', name: 'Fiumicino', city: 'Rome', country: 'Italie', continent: 'Europe', timezone: 'Europe/Rome', coordinates: { lat: 41.8003, lng: 12.2389 } },
  { code: 'BCN', name: 'El Prat', city: 'Barcelone', country: 'Espagne', continent: 'Europe', timezone: 'Europe/Madrid', coordinates: { lat: 41.2971, lng: 2.0785 } },
  { code: 'MAD', name: 'Barajas', city: 'Madrid', country: 'Espagne', continent: 'Europe', timezone: 'Europe/Madrid', coordinates: { lat: 40.4936, lng: -3.5668 } },
  { code: 'AMS', name: 'Schiphol', city: 'Amsterdam', country: 'Pays-Bas', continent: 'Europe', timezone: 'Europe/Amsterdam', coordinates: { lat: 52.3105, lng: 4.7683 } },
  { code: 'FRA', name: 'Frankfurt', city: 'Francfort', country: 'Allemagne', continent: 'Europe', timezone: 'Europe/Berlin', coordinates: { lat: 50.0379, lng: 8.5622 } },
  { code: 'MUC', name: 'Munich', city: 'Munich', country: 'Allemagne', continent: 'Europe', timezone: 'Europe/Berlin', coordinates: { lat: 48.3538, lng: 11.7861 } },
  { code: 'BER', name: 'Brandenburg', city: 'Berlin', country: 'Allemagne', continent: 'Europe', timezone: 'Europe/Berlin', coordinates: { lat: 52.3667, lng: 13.5033 } },
  { code: 'ZRH', name: 'Zurich', city: 'Zurich', country: 'Suisse', continent: 'Europe', timezone: 'Europe/Zurich', coordinates: { lat: 47.4647, lng: 8.5492 } },
  { code: 'VIE', name: 'Vienna', city: 'Vienne', country: 'Autriche', continent: 'Europe', timezone: 'Europe/Vienna', coordinates: { lat: 48.1103, lng: 16.5697 } },
  { code: 'CPH', name: 'Copenhagen', city: 'Copenhague', country: 'Danemark', continent: 'Europe', timezone: 'Europe/Copenhagen', coordinates: { lat: 55.6180, lng: 12.6508 } },
  { code: 'OSL', name: 'Gardermoen', city: 'Oslo', country: 'Norvège', continent: 'Europe', timezone: 'Europe/Oslo', coordinates: { lat: 60.1939, lng: 11.1004 } },
  { code: 'ARN', name: 'Arlanda', city: 'Stockholm', country: 'Suède', continent: 'Europe', timezone: 'Europe/Stockholm', coordinates: { lat: 59.6519, lng: 17.9186 } },
  { code: 'HEL', name: 'Helsinki-Vantaa', city: 'Helsinki', country: 'Finlande', continent: 'Europe', timezone: 'Europe/Helsinki', coordinates: { lat: 60.3172, lng: 24.9633 } },
  { code: 'LIS', name: 'Portela', city: 'Lisbonne', country: 'Portugal', continent: 'Europe', timezone: 'Europe/Lisbon', coordinates: { lat: 38.7813, lng: -9.1359 } },
  { code: 'OPO', name: 'Porto', city: 'Porto', country: 'Portugal', continent: 'Europe', timezone: 'Europe/Lisbon', coordinates: { lat: 41.2481, lng: -8.6814 } },
  { code: 'DUB', name: 'Dublin', city: 'Dublin', country: 'Irlande', continent: 'Europe', timezone: 'Europe/Dublin', coordinates: { lat: 53.4213, lng: -6.2701 } },
  { code: 'BRU', name: 'Brussels', city: 'Bruxelles', country: 'Belgique', continent: 'Europe', timezone: 'Europe/Brussels', coordinates: { lat: 50.9010, lng: 4.4844 } },
  { code: 'PRG', name: 'Vaclav Havel', city: 'Prague', country: 'République Tchèque', continent: 'Europe', timezone: 'Europe/Prague', coordinates: { lat: 50.1008, lng: 14.2600 } },
  { code: 'WAW', name: 'Chopin', city: 'Varsovie', country: 'Pologne', continent: 'Europe', timezone: 'Europe/Warsaw', coordinates: { lat: 52.1657, lng: 20.9671 } },
  { code: 'BUD', name: 'Ferenc Liszt', city: 'Budapest', country: 'Hongrie', continent: 'Europe', timezone: 'Europe/Budapest', coordinates: { lat: 47.4300, lng: 19.2556 } },
  { code: 'ATH', name: 'Eleftherios Venizelos', city: 'Athènes', country: 'Grèce', continent: 'Europe', timezone: 'Europe/Athens', coordinates: { lat: 37.9364, lng: 23.9445 } },
  { code: 'IST', name: 'Istanbul', city: 'Istanbul', country: 'Turquie', continent: 'Europe', timezone: 'Europe/Istanbul', coordinates: { lat: 40.9769, lng: 28.8146 } },
  { code: 'SAW', name: 'Sabiha Gokcen', city: 'Istanbul', country: 'Turquie', continent: 'Europe', timezone: 'Europe/Istanbul', coordinates: { lat: 40.8986, lng: 29.3092 } },
  { code: 'MXP', name: 'Malpensa', city: 'Milan', country: 'Italie', continent: 'Europe', timezone: 'Europe/Rome', coordinates: { lat: 45.6306, lng: 8.7281 } },
  { code: 'VCE', name: 'Marco Polo', city: 'Venise', country: 'Italie', continent: 'Europe', timezone: 'Europe/Rome', coordinates: { lat: 45.5053, lng: 12.3519 } },
  { code: 'NAP', name: 'Capodichino', city: 'Naples', country: 'Italie', continent: 'Europe', timezone: 'Europe/Rome', coordinates: { lat: 40.8860, lng: 14.2908 } },
  { code: 'LYS', name: 'Lyon Saint-Exupéry', city: 'Lyon', country: 'France', continent: 'Europe', timezone: 'Europe/Paris', coordinates: { lat: 45.7256, lng: 5.0811 } },
  { code: 'MRS', name: 'Marseille Provence', city: 'Marseille', country: 'France', continent: 'Europe', timezone: 'Europe/Paris', coordinates: { lat: 43.4393, lng: 5.2214 } },
  { code: 'NCE', name: "Côte d'Azur", city: 'Nice', country: 'France', continent: 'Europe', timezone: 'Europe/Paris', coordinates: { lat: 43.6584, lng: 7.2159 } },
  { code: 'TLS', name: 'Toulouse-Blagnac', city: 'Toulouse', country: 'France', continent: 'Europe', timezone: 'Europe/Paris', coordinates: { lat: 43.6291, lng: 1.3638 } },
  { code: 'BOD', name: 'Bordeaux-Mérignac', city: 'Bordeaux', country: 'France', continent: 'Europe', timezone: 'Europe/Paris', coordinates: { lat: 44.8283, lng: -0.7155 } },
  { code: 'NTE', name: 'Nantes Atlantique', city: 'Nantes', country: 'France', continent: 'Europe', timezone: 'Europe/Paris', coordinates: { lat: 47.1532, lng: -1.6108 } },
  { code: 'GVA', name: 'Geneva', city: 'Genève', country: 'Suisse', continent: 'Europe', timezone: 'Europe/Zurich', coordinates: { lat: 46.2381, lng: 6.1090 } },
  { code: 'BSL', name: 'EuroAirport', city: 'Bâle', country: 'Suisse', continent: 'Europe', timezone: 'Europe/Zurich', coordinates: { lat: 47.5900, lng: 7.5291 } },
  { code: 'INN', name: 'Innsbruck', city: 'Innsbruck', country: 'Autriche', continent: 'Europe', timezone: 'Europe/Vienna', coordinates: { lat: 47.2602, lng: 11.3439 } },
  { code: 'SZG', name: 'Salzburg', city: 'Salzbourg', country: 'Autriche', continent: 'Europe', timezone: 'Europe/Vienna', coordinates: { lat: 47.7933, lng: 13.0043 } },
  { code: 'AGP', name: 'Málaga-Costa del Sol', city: 'Málaga', country: 'Espagne', continent: 'Europe', timezone: 'Europe/Madrid', coordinates: { lat: 36.6749, lng: -4.4991 } },
  { code: 'SVQ', name: 'Sevilla', city: 'Séville', country: 'Espagne', continent: 'Europe', timezone: 'Europe/Madrid', coordinates: { lat: 37.4180, lng: -5.8931 } },
  { code: 'PMI', name: 'Palma de Mallorca', city: 'Palma de Majorque', country: 'Espagne', continent: 'Europe', timezone: 'Europe/Madrid', coordinates: { lat: 39.5517, lng: 2.7388 } },
  { code: 'ALC', name: 'Alicante', city: 'Alicante', country: 'Espagne', continent: 'Europe', timezone: 'Europe/Madrid', coordinates: { lat: 38.2822, lng: -0.5581 } },
  { code: 'VLC', name: 'Valencia', city: 'Valence', country: 'Espagne', continent: 'Europe', timezone: 'Europe/Madrid', coordinates: { lat: 39.4893, lng: -0.4817 } },
  { code: 'BIO', name: 'Bilbao', city: 'Bilbao', country: 'Espagne', continent: 'Europe', timezone: 'Europe/Madrid', coordinates: { lat: 43.3011, lng: -2.9106 } },
  { code: 'IBZ', name: 'Ibiza', city: 'Ibiza', country: 'Espagne', continent: 'Europe', timezone: 'Europe/Madrid', coordinates: { lat: 38.8729, lng: 1.3731 } },
  { code: 'FAO', name: 'Faro', city: 'Faro', country: 'Portugal', continent: 'Europe', timezone: 'Europe/Lisbon', coordinates: { lat: 37.0144, lng: -7.9659 } },
  { code: 'EDI', name: 'Edinburgh', city: 'Édimbourg', country: 'Royaume-Uni', continent: 'Europe', timezone: 'Europe/London', coordinates: { lat: 55.9500, lng: -3.3725 } },
  { code: 'MAN', name: 'Manchester', city: 'Manchester', country: 'Royaume-Uni', continent: 'Europe', timezone: 'Europe/London', coordinates: { lat: 53.3537, lng: -2.2750 } },
  { code: 'GLA', name: 'Glasgow', city: 'Glasgow', country: 'Royaume-Uni', continent: 'Europe', timezone: 'Europe/London', coordinates: { lat: 55.8719, lng: -4.4333 } },
  { code: 'BHX', name: 'Birmingham', city: 'Birmingham', country: 'Royaume-Uni', continent: 'Europe', timezone: 'Europe/London', coordinates: { lat: 52.4539, lng: -1.7480 } },
  { code: 'BRS', name: 'Bristol', city: 'Bristol', country: 'Royaume-Uni', continent: 'Europe', timezone: 'Europe/London', coordinates: { lat: 51.3827, lng: -2.7190 } },
  { code: 'LPA', name: 'Gran Canaria', city: 'Las Palmas', country: 'Espagne', continent: 'Europe', timezone: 'Atlantic/Canary', coordinates: { lat: 27.9319, lng: -15.3866 } },
  { code: 'TFS', name: 'Tenerife Sur', city: 'Tenerife', country: 'Espagne', continent: 'Europe', timezone: 'Atlantic/Canary', coordinates: { lat: 28.0445, lng: -16.5725 } },
  { code: 'ACE', name: 'Lanzarote', city: 'Arrecife', country: 'Espagne', continent: 'Europe', timezone: 'Atlantic/Canary', coordinates: { lat: 28.9455, lng: -13.6052 } },
  { code: 'OTP', name: 'Henri Coandă', city: 'Bucarest', country: 'Roumanie', continent: 'Europe', timezone: 'Europe/Bucharest', coordinates: { lat: 44.5711, lng: 26.0850 } },
  { code: 'SOF', name: 'Sofia', city: 'Sofia', country: 'Bulgarie', continent: 'Europe', timezone: 'Europe/Sofia', coordinates: { lat: 42.6952, lng: 23.4114 } },
  { code: 'SKG', name: 'Thessaloniki', city: 'Thessalonique', country: 'Grèce', continent: 'Europe', timezone: 'Europe/Athens', coordinates: { lat: 40.5197, lng: 22.9709 } },
  { code: 'HER', name: 'Heraklion', city: 'Héraklion', country: 'Grèce', continent: 'Europe', timezone: 'Europe/Athens', coordinates: { lat: 35.3397, lng: 25.1803 } },
  { code: 'RHO', name: 'Rhodes', city: 'Rhodes', country: 'Grèce', continent: 'Europe', timezone: 'Europe/Athens', coordinates: { lat: 36.4054, lng: 28.0862 } },
  { code: 'CFU', name: 'Corfu', city: 'Corfou', country: 'Grèce', continent: 'Europe', timezone: 'Europe/Athens', coordinates: { lat: 39.6019, lng: 19.9117 } },
  { code: 'KRK', name: 'John Paul II', city: 'Cracovie', country: 'Pologne', continent: 'Europe', timezone: 'Europe/Warsaw', coordinates: { lat: 50.0777, lng: 19.7848 } },
  { code: 'BEG', name: 'Belgrade Nikola Tesla', city: 'Belgrade', country: 'Serbie', continent: 'Europe', timezone: 'Europe/Belgrade', coordinates: { lat: 44.8184, lng: 20.3091 } },
  { code: 'ZAG', name: 'Zagreb', city: 'Zagreb', country: 'Croatie', continent: 'Europe', timezone: 'Europe/Zagreb', coordinates: { lat: 45.7429, lng: 16.0688 } },
  { code: 'SPU', name: 'Split', city: 'Split', country: 'Croatie', continent: 'Europe', timezone: 'Europe/Zagreb', coordinates: { lat: 43.5389, lng: 16.2980 } },
  { code: 'DBV', name: 'Dubrovnik', city: 'Dubrovnik', country: 'Croatie', continent: 'Europe', timezone: 'Europe/Zagreb', coordinates: { lat: 42.5614, lng: 18.2682 } },
  { code: 'RIX', name: 'Riga', city: 'Riga', country: 'Lettonie', continent: 'Europe', timezone: 'Europe/Riga', coordinates: { lat: 56.9236, lng: 23.9711 } },
  { code: 'TLL', name: 'Tallinn', city: 'Tallinn', country: 'Estonie', continent: 'Europe', timezone: 'Europe/Tallinn', coordinates: { lat: 59.4133, lng: 24.8328 } },
  { code: 'VNO', name: 'Vilnius', city: 'Vilnius', country: 'Lituanie', continent: 'Europe', timezone: 'Europe/Vilnius', coordinates: { lat: 54.6341, lng: 25.2858 } },
  { code: 'KEF', name: 'Keflavik', city: 'Reykjavik', country: 'Islande', continent: 'Europe', timezone: 'Atlantic/Reykjavik', coordinates: { lat: 63.9850, lng: -22.6056 } },
  { code: 'LUX', name: 'Luxembourg', city: 'Luxembourg', country: 'Luxembourg', continent: 'Europe', timezone: 'Europe/Luxembourg', coordinates: { lat: 49.6233, lng: 6.2044 } },
  { code: 'MLT', name: 'Malta', city: 'La Valette', country: 'Malte', continent: 'Europe', timezone: 'Europe/Malta', coordinates: { lat: 35.8575, lng: 14.4775 } },
  { code: 'CAG', name: 'Cagliari', city: 'Cagliari', country: 'Italie', continent: 'Europe', timezone: 'Europe/Rome', coordinates: { lat: 39.2515, lng: 9.0543 } },
  { code: 'CTA', name: 'Catania', city: 'Catane', country: 'Italie', continent: 'Europe', timezone: 'Europe/Rome', coordinates: { lat: 37.4668, lng: 15.0664 } },
  { code: 'PMO', name: 'Palermo', city: 'Palerme', country: 'Italie', continent: 'Europe', timezone: 'Europe/Rome', coordinates: { lat: 38.1759, lng: 13.0910 } },
  { code: 'BLQ', name: 'Bologna', city: 'Bologne', country: 'Italie', continent: 'Europe', timezone: 'Europe/Rome', coordinates: { lat: 44.5354, lng: 11.2887 } },
  { code: 'FLR', name: 'Florence', city: 'Florence', country: 'Italie', continent: 'Europe', timezone: 'Europe/Rome', coordinates: { lat: 43.8100, lng: 11.2051 } },
  { code: 'TRN', name: 'Turin', city: 'Turin', country: 'Italie', continent: 'Europe', timezone: 'Europe/Rome', coordinates: { lat: 45.2008, lng: 7.6493 } },
  { code: 'GOT', name: 'Gothenburg', city: 'Göteborg', country: 'Suède', continent: 'Europe', timezone: 'Europe/Stockholm', coordinates: { lat: 57.6628, lng: 12.2798 } },
  { code: 'BGO', name: 'Bergen', city: 'Bergen', country: 'Norvège', continent: 'Europe', timezone: 'Europe/Oslo', coordinates: { lat: 60.2934, lng: 5.2181 } },
  { code: 'AAL', name: 'Aalborg', city: 'Aalborg', country: 'Danemark', continent: 'Europe', timezone: 'Europe/Copenhagen', coordinates: { lat: 57.0928, lng: 9.8492 } },
  { code: 'STR', name: 'Stuttgart', city: 'Stuttgart', country: 'Allemagne', continent: 'Europe', timezone: 'Europe/Berlin', coordinates: { lat: 48.6899, lng: 9.2219 } },
  { code: 'DUS', name: 'Düsseldorf', city: 'Düsseldorf', country: 'Allemagne', continent: 'Europe', timezone: 'Europe/Berlin', coordinates: { lat: 51.2895, lng: 6.7668 } },
  { code: 'HAM', name: 'Hamburg', city: 'Hambourg', country: 'Allemagne', continent: 'Europe', timezone: 'Europe/Berlin', coordinates: { lat: 53.6304, lng: 9.9882 } },
  { code: 'CGN', name: 'Cologne Bonn', city: 'Cologne', country: 'Allemagne', continent: 'Europe', timezone: 'Europe/Berlin', coordinates: { lat: 50.8659, lng: 7.1427 } },
  { code: 'BIA', name: 'Bastia', city: 'Bastia', country: 'France', continent: 'Europe', timezone: 'Europe/Paris', coordinates: { lat: 42.5527, lng: 9.4837 } },
  { code: 'AJA', name: 'Ajaccio', city: 'Ajaccio', country: 'France', continent: 'Europe', timezone: 'Europe/Paris', coordinates: { lat: 41.9236, lng: 8.8029 } },
  { code: 'CFE', name: 'Clermont-Ferrand', city: 'Clermont-Ferrand', country: 'France', continent: 'Europe', timezone: 'Europe/Paris', coordinates: { lat: 45.7867, lng: 3.1692 } },
  { code: 'MPL', name: 'Montpellier', city: 'Montpellier', country: 'France', continent: 'Europe', timezone: 'Europe/Paris', coordinates: { lat: 43.5762, lng: 3.9630 } },
  { code: 'RNS', name: 'Rennes', city: 'Rennes', country: 'France', continent: 'Europe', timezone: 'Europe/Paris', coordinates: { lat: 48.0695, lng: -1.7348 } },
  { code: 'SXB', name: 'Strasbourg', city: 'Strasbourg', country: 'France', continent: 'Europe', timezone: 'Europe/Paris', coordinates: { lat: 48.5383, lng: 7.6283 } },

  // Asie - Principaux hubs
  { code: 'NRT', name: 'Narita', city: 'Tokyo', country: 'Japon', continent: 'Asie', timezone: 'Asia/Tokyo', coordinates: { lat: 35.7720, lng: 140.3929 } },
  { code: 'HND', name: 'Haneda', city: 'Tokyo', country: 'Japon', continent: 'Asie', timezone: 'Asia/Tokyo', coordinates: { lat: 35.5494, lng: 139.7798 } },
  { code: 'KIX', name: 'Kansai', city: 'Osaka', country: 'Japon', continent: 'Asie', timezone: 'Asia/Tokyo', coordinates: { lat: 34.4273, lng: 135.2444 } },
  { code: 'BKK', name: 'Suvarnabhumi', city: 'Bangkok', country: 'Thaïlande', continent: 'Asie', timezone: 'Asia/Bangkok', coordinates: { lat: 13.6811, lng: 100.7472 } },
  { code: 'DMK', name: 'Don Mueang', city: 'Bangkok', country: 'Thaïlande', continent: 'Asie', timezone: 'Asia/Bangkok', coordinates: { lat: 13.9126, lng: 100.6070 } },
  { code: 'SIN', name: 'Changi', city: 'Singapour', country: 'Singapour', continent: 'Asie', timezone: 'Asia/Singapore', coordinates: { lat: 1.3644, lng: 103.9915 } },
  { code: 'HKG', name: 'Hong Kong', city: 'Hong Kong', country: 'Chine', continent: 'Asie', timezone: 'Asia/Hong_Kong', coordinates: { lat: 22.3080, lng: 113.9185 } },
  { code: 'PVG', name: 'Pudong', city: 'Shanghai', country: 'Chine', continent: 'Asie', timezone: 'Asia/Shanghai', coordinates: { lat: 31.1434, lng: 121.8052 } },
  { code: 'PEK', name: 'Beijing Capital', city: 'Pékin', country: 'Chine', continent: 'Asie', timezone: 'Asia/Shanghai', coordinates: { lat: 40.0799, lng: 116.6031 } },
  { code: 'ICN', name: 'Incheon', city: 'Séoul', country: 'Corée du Sud', continent: 'Asie', timezone: 'Asia/Seoul', coordinates: { lat: 37.4602, lng: 126.4407 } },
  { code: 'DXB', name: 'Dubai', city: 'Dubaï', country: 'Émirats Arabes Unis', continent: 'Asie', timezone: 'Asia/Dubai', coordinates: { lat: 25.2532, lng: 55.3657 } },
  { code: 'AUH', name: 'Abu Dhabi', city: 'Abu Dhabi', country: 'Émirats Arabes Unis', continent: 'Asie', timezone: 'Asia/Dubai', coordinates: { lat: 24.4330, lng: 54.6511 } },
  { code: 'DOH', name: 'Hamad', city: 'Doha', country: 'Qatar', continent: 'Asie', timezone: 'Asia/Qatar', coordinates: { lat: 25.2731, lng: 51.6080 } },
  { code: 'KUL', name: 'Kuala Lumpur', city: 'Kuala Lumpur', country: 'Malaisie', continent: 'Asie', timezone: 'Asia/Kuala_Lumpur', coordinates: { lat: 2.7456, lng: 101.7099 } },
  { code: 'CGK', name: 'Soekarno-Hatta', city: 'Jakarta', country: 'Indonésie', continent: 'Asie', timezone: 'Asia/Jakarta', coordinates: { lat: -6.1256, lng: 106.6559 } },
  { code: 'DPS', name: 'Ngurah Rai', city: 'Bali', country: 'Indonésie', continent: 'Asie', timezone: 'Asia/Makassar', coordinates: { lat: -8.7482, lng: 115.1670 } },
  { code: 'MNL', name: 'Ninoy Aquino', city: 'Manille', country: 'Philippines', continent: 'Asie', timezone: 'Asia/Manila', coordinates: { lat: 14.5086, lng: 121.0194 } },
  { code: 'HAN', name: 'Noi Bai', city: 'Hanoï', country: 'Vietnam', continent: 'Asie', timezone: 'Asia/Ho_Chi_Minh', coordinates: { lat: 21.2212, lng: 105.8072 } },
  { code: 'SGN', name: 'Tan Son Nhat', city: 'Ho Chi Minh', country: 'Vietnam', continent: 'Asie', timezone: 'Asia/Ho_Chi_Minh', coordinates: { lat: 10.8188, lng: 106.6519 } },
  { code: 'DEL', name: 'Indira Gandhi', city: 'New Delhi', country: 'Inde', continent: 'Asie', timezone: 'Asia/Kolkata', coordinates: { lat: 28.5562, lng: 77.1000 } },
  { code: 'BOM', name: 'Chhatrapati Shivaji', city: 'Mumbai', country: 'Inde', continent: 'Asie', timezone: 'Asia/Kolkata', coordinates: { lat: 19.0896, lng: 72.8656 } },
  { code: 'HKT', name: 'Phuket', city: 'Phuket', country: 'Thaïlande', continent: 'Asie', timezone: 'Asia/Bangkok', coordinates: { lat: 8.1132, lng: 98.3169 } },
  { code: 'CNX', name: 'Chiang Mai', city: 'Chiang Mai', country: 'Thaïlande', continent: 'Asie', timezone: 'Asia/Bangkok', coordinates: { lat: 18.7677, lng: 98.9628 } },
  { code: 'USM', name: 'Koh Samui', city: 'Koh Samui', country: 'Thaïlande', continent: 'Asie', timezone: 'Asia/Bangkok', coordinates: { lat: 9.5478, lng: 100.0623 } },
  { code: 'KBV', name: 'Krabi', city: 'Krabi', country: 'Thaïlande', continent: 'Asie', timezone: 'Asia/Bangkok', coordinates: { lat: 8.0991, lng: 98.9862 } },
  { code: 'CAN', name: 'Guangzhou Baiyun', city: 'Canton', country: 'Chine', continent: 'Asie', timezone: 'Asia/Shanghai', coordinates: { lat: 23.3924, lng: 113.2988 } },
  { code: 'SZX', name: 'Shenzhen Bao\'an', city: 'Shenzhen', country: 'Chine', continent: 'Asie', timezone: 'Asia/Shanghai', coordinates: { lat: 22.6393, lng: 113.8108 } },
  { code: 'CTU', name: 'Chengdu Shuangliu', city: 'Chengdu', country: 'Chine', continent: 'Asie', timezone: 'Asia/Shanghai', coordinates: { lat: 30.5785, lng: 103.9470 } },
  { code: 'XIY', name: 'Xi\'an Xianyang', city: 'Xi\'an', country: 'Chine', continent: 'Asie', timezone: 'Asia/Shanghai', coordinates: { lat: 34.4471, lng: 108.7519 } },
  { code: 'CKG', name: 'Chongqing Jiangbei', city: 'Chongqing', country: 'Chine', continent: 'Asie', timezone: 'Asia/Shanghai', coordinates: { lat: 29.7192, lng: 106.6417 } },
  { code: 'TPE', name: 'Taiwan Taoyuan', city: 'Taipei', country: 'Taïwan', continent: 'Asie', timezone: 'Asia/Taipei', coordinates: { lat: 25.0777, lng: 121.2328 } },
  { code: 'MFM', name: 'Macau', city: 'Macao', country: 'Chine', continent: 'Asie', timezone: 'Asia/Macau', coordinates: { lat: 22.1496, lng: 113.5918 } },
  { code: 'FUK', name: 'Fukuoka', city: 'Fukuoka', country: 'Japon', continent: 'Asie', timezone: 'Asia/Tokyo', coordinates: { lat: 33.5859, lng: 130.4511 } },
  { code: 'CTS', name: 'New Chitose', city: 'Sapporo', country: 'Japon', continent: 'Asie', timezone: 'Asia/Tokyo', coordinates: { lat: 42.7752, lng: 141.6920 } },
  { code: 'NGO', name: 'Chubu Centrair', city: 'Nagoya', country: 'Japon', continent: 'Asie', timezone: 'Asia/Tokyo', coordinates: { lat: 34.8584, lng: 136.8054 } },
  { code: 'GMP', name: 'Gimpo', city: 'Séoul', country: 'Corée du Sud', continent: 'Asie', timezone: 'Asia/Seoul', coordinates: { lat: 37.5583, lng: 126.7906 } },
  { code: 'PUS', name: 'Gimhae', city: 'Busan', country: 'Corée du Sud', continent: 'Asie', timezone: 'Asia/Seoul', coordinates: { lat: 35.1795, lng: 128.9382 } },
  { code: 'BLR', name: 'Kempegowda', city: 'Bangalore', country: 'Inde', continent: 'Asie', timezone: 'Asia/Kolkata', coordinates: { lat: 13.1979, lng: 77.7063 } },
  { code: 'MAA', name: 'Chennai', city: 'Chennai', country: 'Inde', continent: 'Asie', timezone: 'Asia/Kolkata', coordinates: { lat: 12.9941, lng: 80.1709 } },
  { code: 'HYD', name: 'Rajiv Gandhi', city: 'Hyderabad', country: 'Inde', continent: 'Asie', timezone: 'Asia/Kolkata', coordinates: { lat: 17.2403, lng: 78.4294 } },
  { code: 'CCU', name: 'Netaji Subhas Chandra Bose', city: 'Kolkata', country: 'Inde', continent: 'Asie', timezone: 'Asia/Kolkata', coordinates: { lat: 22.6547, lng: 88.4467 } },
  { code: 'GOI', name: 'Goa', city: 'Goa', country: 'Inde', continent: 'Asie', timezone: 'Asia/Kolkata', coordinates: { lat: 15.3808, lng: 73.8314 } },
  { code: 'CMB', name: 'Bandaranaike', city: 'Colombo', country: 'Sri Lanka', continent: 'Asie', timezone: 'Asia/Colombo', coordinates: { lat: 7.1808, lng: 79.8841 } },
  { code: 'RGN', name: 'Yangon', city: 'Yangon', country: 'Myanmar', continent: 'Asie', timezone: 'Asia/Yangon', coordinates: { lat: 16.9073, lng: 96.1332 } },
  { code: 'DAD', name: 'Da Nang', city: 'Da Nang', country: 'Vietnam', continent: 'Asie', timezone: 'Asia/Ho_Chi_Minh', coordinates: { lat: 16.0439, lng: 108.1994 } },
  { code: 'PNH', name: 'Phnom Penh', city: 'Phnom Penh', country: 'Cambodge', continent: 'Asie', timezone: 'Asia/Phnom_Penh', coordinates: { lat: 11.5466, lng: 104.8442 } },
  { code: 'REP', name: 'Siem Reap', city: 'Siem Reap', country: 'Cambodge', continent: 'Asie', timezone: 'Asia/Phnom_Penh', coordinates: { lat: 13.4107, lng: 103.8130 } },
  { code: 'VTE', name: 'Wattay', city: 'Vientiane', country: 'Laos', continent: 'Asie', timezone: 'Asia/Vientiane', coordinates: { lat: 17.9883, lng: 102.5633 } },
  { code: 'BWN', name: 'Brunei', city: 'Bandar Seri Begawan', country: 'Brunei', continent: 'Asie', timezone: 'Asia/Brunei', coordinates: { lat: 4.9442, lng: 114.9286 } },
  { code: 'SUB', name: 'Juanda', city: 'Surabaya', country: 'Indonésie', continent: 'Asie', timezone: 'Asia/Jakarta', coordinates: { lat: -7.3798, lng: 112.7869 } },
  { code: 'UPG', name: 'Hasanuddin', city: 'Makassar', country: 'Indonésie', continent: 'Asie', timezone: 'Asia/Makassar', coordinates: { lat: -5.0616, lng: 119.5540 } },
  { code: 'LOP', name: 'Lombok', city: 'Praya', country: 'Indonésie', continent: 'Asie', timezone: 'Asia/Makassar', coordinates: { lat: -8.7573, lng: 116.2768 } },
  { code: 'CEB', name: 'Mactan-Cebu', city: 'Cebu', country: 'Philippines', continent: 'Asie', timezone: 'Asia/Manila', coordinates: { lat: 10.3075, lng: 123.9790 } },
  { code: 'CRK', name: 'Clark', city: 'Angeles', country: 'Philippines', continent: 'Asie', timezone: 'Asia/Manila', coordinates: { lat: 15.1859, lng: 120.5602 } },
  { code: 'PEN', name: 'Penang', city: 'George Town', country: 'Malaisie', continent: 'Asie', timezone: 'Asia/Kuala_Lumpur', coordinates: { lat: 5.2971, lng: 100.2770 } },
  { code: 'JHB', name: 'Senai', city: 'Johor Bahru', country: 'Malaisie', continent: 'Asie', timezone: 'Asia/Kuala_Lumpur', coordinates: { lat: 1.6411, lng: 103.6697 } },
  { code: 'KHI', name: 'Jinnah', city: 'Karachi', country: 'Pakistan', continent: 'Asie', timezone: 'Asia/Karachi', coordinates: { lat: 24.9065, lng: 67.1608 } },
  { code: 'LHE', name: 'Allama Iqbal', city: 'Lahore', country: 'Pakistan', continent: 'Asie', timezone: 'Asia/Karachi', coordinates: { lat: 31.5216, lng: 74.4036 } },
  { code: 'ISB', name: 'Islamabad', city: 'Islamabad', country: 'Pakistan', continent: 'Asie', timezone: 'Asia/Karachi', coordinates: { lat: 33.6169, lng: 73.0992 } },
  { code: 'DAC', name: 'Dhaka', city: 'Dacca', country: 'Bangladesh', continent: 'Asie', timezone: 'Asia/Dhaka', coordinates: { lat: 23.8433, lng: 90.3978 } },
  { code: 'KTM', name: 'Tribhuvan', city: 'Katmandou', country: 'Népal', continent: 'Asie', timezone: 'Asia/Kathmandu', coordinates: { lat: 27.6966, lng: 85.3591 } },
  { code: 'TBS', name: 'Tbilisi', city: 'Tbilissi', country: 'Géorgie', continent: 'Asie', timezone: 'Asia/Tbilisi', coordinates: { lat: 41.6692, lng: 44.9547 } },
  { code: 'EVN', name: 'Yerevan', city: 'Erevan', country: 'Arménie', continent: 'Asie', timezone: 'Asia/Yerevan', coordinates: { lat: 40.1473, lng: 44.3959 } },
  { code: 'GYD', name: 'Heydar Aliyev', city: 'Bakou', country: 'Azerbaïdjan', continent: 'Asie', timezone: 'Asia/Baku', coordinates: { lat: 40.4675, lng: 50.0467 } },
  { code: 'MCT', name: 'Muscat', city: 'Mascate', country: 'Oman', continent: 'Asie', timezone: 'Asia/Muscat', coordinates: { lat: 23.5933, lng: 58.2844 } },
  { code: 'BAH', name: 'Bahrain', city: 'Manama', country: 'Bahreïn', continent: 'Asie', timezone: 'Asia/Bahrain', coordinates: { lat: 26.2708, lng: 50.6336 } },
  { code: 'KWI', name: 'Kuwait', city: 'Koweït', country: 'Koweït', continent: 'Asie', timezone: 'Asia/Kuwait', coordinates: { lat: 29.2267, lng: 47.9689 } },
  { code: 'AMM', name: 'Queen Alia', city: 'Amman', country: 'Jordanie', continent: 'Asie', timezone: 'Asia/Amman', coordinates: { lat: 31.7226, lng: 35.9932 } },
  { code: 'BEY', name: 'Rafic Hariri', city: 'Beyrouth', country: 'Liban', continent: 'Asie', timezone: 'Asia/Beirut', coordinates: { lat: 33.8209, lng: 35.4884 } },
  { code: 'TLV', name: 'Ben Gurion', city: 'Tel Aviv', country: 'Israël', continent: 'Asie', timezone: 'Asia/Jerusalem', coordinates: { lat: 32.0114, lng: 34.8867 } },
  { code: 'SHJ', name: 'Sharjah', city: 'Sharjah', country: 'Émirats Arabes Unis', continent: 'Asie', timezone: 'Asia/Dubai', coordinates: { lat: 25.3286, lng: 55.5172 } },
  { code: 'ALA', name: 'Almaty', city: 'Almaty', country: 'Kazakhstan', continent: 'Asie', timezone: 'Asia/Almaty', coordinates: { lat: 43.3521, lng: 77.0405 } },
  { code: 'NQZ', name: 'Nursultan Nazarbayev', city: 'Astana', country: 'Kazakhstan', continent: 'Asie', timezone: 'Asia/Almaty', coordinates: { lat: 51.0222, lng: 71.4669 } },
  { code: 'TAS', name: 'Tashkent', city: 'Tachkent', country: 'Ouzbékistan', continent: 'Asie', timezone: 'Asia/Tashkent', coordinates: { lat: 41.2579, lng: 69.2811 } },

  // Amérique du Nord
  { code: 'JFK', name: 'John F. Kennedy', city: 'New York', country: 'États-Unis', continent: 'Amérique du Nord', timezone: 'America/New_York', coordinates: { lat: 40.6413, lng: -73.7781 } },
  { code: 'EWR', name: 'Newark', city: 'New York', country: 'États-Unis', continent: 'Amérique du Nord', timezone: 'America/New_York', coordinates: { lat: 40.6895, lng: -74.1745 } },
  { code: 'LAX', name: 'Los Angeles', city: 'Los Angeles', country: 'États-Unis', continent: 'Amérique du Nord', timezone: 'America/Los_Angeles', coordinates: { lat: 33.9416, lng: -118.4085 } },
  { code: 'SFO', name: 'San Francisco', city: 'San Francisco', country: 'États-Unis', continent: 'Amérique du Nord', timezone: 'America/Los_Angeles', coordinates: { lat: 37.6213, lng: -122.3790 } },
  { code: 'MIA', name: 'Miami', city: 'Miami', country: 'États-Unis', continent: 'Amérique du Nord', timezone: 'America/New_York', coordinates: { lat: 25.7959, lng: -80.2870 } },
  { code: 'ORD', name: "O'Hare", city: 'Chicago', country: 'États-Unis', continent: 'Amérique du Nord', timezone: 'America/Chicago', coordinates: { lat: 41.9742, lng: -87.9073 } },
  { code: 'DFW', name: 'Dallas/Fort Worth', city: 'Dallas', country: 'États-Unis', continent: 'Amérique du Nord', timezone: 'America/Chicago', coordinates: { lat: 32.8998, lng: -97.0403 } },
  { code: 'ATL', name: 'Hartsfield-Jackson', city: 'Atlanta', country: 'États-Unis', continent: 'Amérique du Nord', timezone: 'America/New_York', coordinates: { lat: 33.6407, lng: -84.4277 } },
  { code: 'SEA', name: 'Seattle-Tacoma', city: 'Seattle', country: 'États-Unis', continent: 'Amérique du Nord', timezone: 'America/Los_Angeles', coordinates: { lat: 47.4502, lng: -122.3088 } },
  { code: 'LAS', name: 'McCarran', city: 'Las Vegas', country: 'États-Unis', continent: 'Amérique du Nord', timezone: 'America/Los_Angeles', coordinates: { lat: 36.0840, lng: -115.1537 } },
  { code: 'YYZ', name: 'Toronto Pearson', city: 'Toronto', country: 'Canada', continent: 'Amérique du Nord', timezone: 'America/Toronto', coordinates: { lat: 43.6777, lng: -79.6248 } },
  { code: 'YVR', name: 'Vancouver', city: 'Vancouver', country: 'Canada', continent: 'Amérique du Nord', timezone: 'America/Vancouver', coordinates: { lat: 49.1967, lng: -123.1815 } },
  { code: 'YUL', name: 'Montréal-Trudeau', city: 'Montréal', country: 'Canada', continent: 'Amérique du Nord', timezone: 'America/Toronto', coordinates: { lat: 45.4657, lng: -73.7455 } },
  { code: 'MEX', name: 'Mexico City', city: 'Mexico', country: 'Mexique', continent: 'Amérique du Nord', timezone: 'America/Mexico_City', coordinates: { lat: 19.4363, lng: -99.0721 } },
  { code: 'CUN', name: 'Cancún', city: 'Cancún', country: 'Mexique', continent: 'Amérique du Nord', timezone: 'America/Cancun', coordinates: { lat: 21.0365, lng: -86.8770 } },
  { code: 'BOS', name: 'Logan', city: 'Boston', country: 'États-Unis', continent: 'Amérique du Nord', timezone: 'America/New_York', coordinates: { lat: 42.3656, lng: -71.0096 } },
  { code: 'DEN', name: 'Denver', city: 'Denver', country: 'États-Unis', continent: 'Amérique du Nord', timezone: 'America/Denver', coordinates: { lat: 39.8561, lng: -104.6737 } },
  { code: 'PHX', name: 'Phoenix Sky Harbor', city: 'Phoenix', country: 'États-Unis', continent: 'Amérique du Nord', timezone: 'America/Phoenix', coordinates: { lat: 33.4342, lng: -112.0080 } },
  { code: 'IAH', name: 'George Bush', city: 'Houston', country: 'États-Unis', continent: 'Amérique du Nord', timezone: 'America/Chicago', coordinates: { lat: 29.9902, lng: -95.3368 } },
  { code: 'MCO', name: 'Orlando', city: 'Orlando', country: 'États-Unis', continent: 'Amérique du Nord', timezone: 'America/New_York', coordinates: { lat: 28.4312, lng: -81.3081 } },
  { code: 'MSP', name: 'Minneapolis-St Paul', city: 'Minneapolis', country: 'États-Unis', continent: 'Amérique du Nord', timezone: 'America/Chicago', coordinates: { lat: 44.8848, lng: -93.2223 } },
  { code: 'DTW', name: 'Detroit Metropolitan', city: 'Detroit', country: 'États-Unis', continent: 'Amérique du Nord', timezone: 'America/Detroit', coordinates: { lat: 42.2162, lng: -83.3554 } },
  { code: 'PHL', name: 'Philadelphia', city: 'Philadelphie', country: 'États-Unis', continent: 'Amérique du Nord', timezone: 'America/New_York', coordinates: { lat: 39.8729, lng: -75.2437 } },
  { code: 'SAN', name: 'San Diego', city: 'San Diego', country: 'États-Unis', continent: 'Amérique du Nord', timezone: 'America/Los_Angeles', coordinates: { lat: 32.7338, lng: -117.1933 } },
  { code: 'SLC', name: 'Salt Lake City', city: 'Salt Lake City', country: 'États-Unis', continent: 'Amérique du Nord', timezone: 'America/Denver', coordinates: { lat: 40.7884, lng: -111.9778 } },
  { code: 'PDX', name: 'Portland', city: 'Portland', country: 'États-Unis', continent: 'Amérique du Nord', timezone: 'America/Los_Angeles', coordinates: { lat: 45.5887, lng: -122.5975 } },
  { code: 'TPA', name: 'Tampa', city: 'Tampa', country: 'États-Unis', continent: 'Amérique du Nord', timezone: 'America/New_York', coordinates: { lat: 27.9755, lng: -82.5332 } },
  { code: 'MSY', name: 'New Orleans', city: 'La Nouvelle-Orléans', country: 'États-Unis', continent: 'Amérique du Nord', timezone: 'America/Chicago', coordinates: { lat: 29.9934, lng: -90.2580 } },
  { code: 'AUS', name: 'Austin-Bergstrom', city: 'Austin', country: 'États-Unis', continent: 'Amérique du Nord', timezone: 'America/Chicago', coordinates: { lat: 30.1975, lng: -97.6664 } },
  { code: 'BNA', name: 'Nashville', city: 'Nashville', country: 'États-Unis', continent: 'Amérique du Nord', timezone: 'America/Chicago', coordinates: { lat: 36.1245, lng: -86.6782 } },
  { code: 'CLT', name: 'Charlotte Douglas', city: 'Charlotte', country: 'États-Unis', continent: 'Amérique du Nord', timezone: 'America/New_York', coordinates: { lat: 35.2144, lng: -80.9473 } },
  { code: 'STL', name: 'St. Louis Lambert', city: 'Saint-Louis', country: 'États-Unis', continent: 'Amérique du Nord', timezone: 'America/Chicago', coordinates: { lat: 38.7487, lng: -90.3700 } },
  { code: 'BWI', name: 'Baltimore/Washington', city: 'Baltimore', country: 'États-Unis', continent: 'Amérique du Nord', timezone: 'America/New_York', coordinates: { lat: 39.1754, lng: -76.6683 } },
  { code: 'IAD', name: 'Washington Dulles', city: 'Washington', country: 'États-Unis', continent: 'Amérique du Nord', timezone: 'America/New_York', coordinates: { lat: 38.9531, lng: -77.4565 } },
  { code: 'DCA', name: 'Reagan National', city: 'Washington', country: 'États-Unis', continent: 'Amérique du Nord', timezone: 'America/New_York', coordinates: { lat: 38.8521, lng: -77.0377 } },
  { code: 'HNL', name: 'Honolulu', city: 'Honolulu', country: 'États-Unis', continent: 'Amérique du Nord', timezone: 'Pacific/Honolulu', coordinates: { lat: 21.3187, lng: -157.9225 } },
  { code: 'OGG', name: 'Kahului', city: 'Maui', country: 'États-Unis', continent: 'Amérique du Nord', timezone: 'Pacific/Honolulu', coordinates: { lat: 20.8986, lng: -156.4306 } },
  { code: 'KOA', name: 'Kona', city: 'Kailua-Kona', country: 'États-Unis', continent: 'Amérique du Nord', timezone: 'Pacific/Honolulu', coordinates: { lat: 19.7388, lng: -156.0456 } },
  { code: 'ANC', name: 'Anchorage', city: 'Anchorage', country: 'États-Unis', continent: 'Amérique du Nord', timezone: 'America/Anchorage', coordinates: { lat: 61.1744, lng: -149.9962 } },
  { code: 'YYC', name: 'Calgary', city: 'Calgary', country: 'Canada', continent: 'Amérique du Nord', timezone: 'America/Edmonton', coordinates: { lat: 51.1315, lng: -114.0106 } },
  { code: 'YEG', name: 'Edmonton', city: 'Edmonton', country: 'Canada', continent: 'Amérique du Nord', timezone: 'America/Edmonton', coordinates: { lat: 53.3097, lng: -113.5800 } },
  { code: 'YOW', name: 'Ottawa Macdonald-Cartier', city: 'Ottawa', country: 'Canada', continent: 'Amérique du Nord', timezone: 'America/Toronto', coordinates: { lat: 45.3225, lng: -75.6692 } },
  { code: 'YHZ', name: 'Halifax Stanfield', city: 'Halifax', country: 'Canada', continent: 'Amérique du Nord', timezone: 'America/Halifax', coordinates: { lat: 44.8808, lng: -63.5086 } },
  { code: 'YWG', name: 'Winnipeg Richardson', city: 'Winnipeg', country: 'Canada', continent: 'Amérique du Nord', timezone: 'America/Winnipeg', coordinates: { lat: 49.9100, lng: -97.2399 } },
  { code: 'PVR', name: 'Licenciado Gustavo Díaz Ordaz', city: 'Puerto Vallarta', country: 'Mexique', continent: 'Amérique du Nord', timezone: 'America/Mexico_City', coordinates: { lat: 20.6801, lng: -105.2545 } },
  { code: 'GDL', name: 'Miguel Hidalgo', city: 'Guadalajara', country: 'Mexique', continent: 'Amérique du Nord', timezone: 'America/Mexico_City', coordinates: { lat: 20.5218, lng: -103.3119 } },
  { code: 'MTY', name: 'General Mariano Escobedo', city: 'Monterrey', country: 'Mexique', continent: 'Amérique du Nord', timezone: 'America/Monterrey', coordinates: { lat: 25.7785, lng: -100.1069 } },
  { code: 'SJD', name: 'Los Cabos', city: 'San José del Cabo', country: 'Mexique', continent: 'Amérique du Nord', timezone: 'America/Mazatlan', coordinates: { lat: 23.1518, lng: -109.7211 } },
  { code: 'MBJ', name: 'Sangster', city: 'Montego Bay', country: 'Jamaïque', continent: 'Amérique du Nord', timezone: 'America/Jamaica', coordinates: { lat: 18.5037, lng: -77.9133 } },
  { code: 'KIN', name: 'Norman Manley', city: 'Kingston', country: 'Jamaïque', continent: 'Amérique du Nord', timezone: 'America/Jamaica', coordinates: { lat: 17.9357, lng: -76.7875 } },
  { code: 'PUJ', name: 'Punta Cana', city: 'Punta Cana', country: 'République Dominicaine', continent: 'Amérique du Nord', timezone: 'America/Santo_Domingo', coordinates: { lat: 18.5674, lng: -68.3634 } },
  { code: 'SDQ', name: 'Las Américas', city: 'Saint-Domingue', country: 'République Dominicaine', continent: 'Amérique du Nord', timezone: 'America/Santo_Domingo', coordinates: { lat: 18.4297, lng: -69.6689 } },
  { code: 'HAV', name: 'José Martí', city: 'La Havane', country: 'Cuba', continent: 'Amérique du Nord', timezone: 'America/Havana', coordinates: { lat: 22.9892, lng: -82.4091 } },
  { code: 'VRA', name: 'Juan Gualberto Gómez', city: 'Varadero', country: 'Cuba', continent: 'Amérique du Nord', timezone: 'America/Havana', coordinates: { lat: 23.0344, lng: -81.4353 } },
  { code: 'BGI', name: 'Grantley Adams', city: 'Bridgetown', country: 'Barbade', continent: 'Amérique du Nord', timezone: 'America/Barbados', coordinates: { lat: 13.0746, lng: -59.4925 } },
  { code: 'SXM', name: 'Princess Juliana', city: 'Philipsburg', country: 'Saint-Martin', continent: 'Amérique du Nord', timezone: 'America/Lower_Princes', coordinates: { lat: 18.0410, lng: -63.1089 } },
  { code: 'ANU', name: 'V.C. Bird', city: 'Saint John\'s', country: 'Antigua-et-Barbuda', continent: 'Amérique du Nord', timezone: 'America/Antigua', coordinates: { lat: 17.1367, lng: -61.7927 } },
  { code: 'UVF', name: 'Hewanorra', city: 'Vieux Fort', country: 'Sainte-Lucie', continent: 'Amérique du Nord', timezone: 'America/St_Lucia', coordinates: { lat: 13.7332, lng: -60.9526 } },
  { code: 'GND', name: 'Maurice Bishop', city: 'Saint-Georges', country: 'Grenade', continent: 'Amérique du Nord', timezone: 'America/Grenada', coordinates: { lat: 12.0042, lng: -61.7862 } },
  { code: 'TAB', name: 'A.N.R. Robinson', city: 'Scarborough', country: 'Trinité-et-Tobago', continent: 'Amérique du Nord', timezone: 'America/Port_of_Spain', coordinates: { lat: 11.1497, lng: -60.8322 } },
  { code: 'POS', name: 'Piarco', city: 'Port of Spain', country: 'Trinité-et-Tobago', continent: 'Amérique du Nord', timezone: 'America/Port_of_Spain', coordinates: { lat: 10.5953, lng: -61.3372 } },
  { code: 'CUR', name: 'Hato', city: 'Willemstad', country: 'Curaçao', continent: 'Amérique du Nord', timezone: 'America/Curacao', coordinates: { lat: 12.1889, lng: -68.9598 } },
  { code: 'AUA', name: 'Queen Beatrix', city: 'Oranjestad', country: 'Aruba', continent: 'Amérique du Nord', timezone: 'America/Aruba', coordinates: { lat: 12.5014, lng: -70.0152 } },
  { code: 'NAS', name: 'Lynden Pindling', city: 'Nassau', country: 'Bahamas', continent: 'Amérique du Nord', timezone: 'America/Nassau', coordinates: { lat: 25.0390, lng: -77.4662 } },
  { code: 'GCM', name: 'Owen Roberts', city: 'George Town', country: 'Îles Caïmans', continent: 'Amérique du Nord', timezone: 'America/Cayman', coordinates: { lat: 19.2928, lng: -81.3577 } },
  { code: 'BDA', name: 'L.F. Wade', city: 'Hamilton', country: 'Bermudes', continent: 'Amérique du Nord', timezone: 'Atlantic/Bermuda', coordinates: { lat: 32.3640, lng: -64.6787 } },

  // Amérique du Sud
  { code: 'GRU', name: 'Guarulhos', city: 'São Paulo', country: 'Brésil', continent: 'Amérique du Sud', timezone: 'America/Sao_Paulo', coordinates: { lat: -23.4356, lng: -46.4731 } },
  { code: 'GIG', name: 'Galeão', city: 'Rio de Janeiro', country: 'Brésil', continent: 'Amérique du Sud', timezone: 'America/Sao_Paulo', coordinates: { lat: -22.8099, lng: -43.2505 } },
  { code: 'EZE', name: 'Ezeiza', city: 'Buenos Aires', country: 'Argentine', continent: 'Amérique du Sud', timezone: 'America/Argentina/Buenos_Aires', coordinates: { lat: -34.8222, lng: -58.5358 } },
  { code: 'BOG', name: 'El Dorado', city: 'Bogotá', country: 'Colombie', continent: 'Amérique du Sud', timezone: 'America/Bogota', coordinates: { lat: 4.7016, lng: -74.1469 } },
  { code: 'LIM', name: 'Jorge Chávez', city: 'Lima', country: 'Pérou', continent: 'Amérique du Sud', timezone: 'America/Lima', coordinates: { lat: -12.0219, lng: -77.1143 } },
  { code: 'SCL', name: 'Arturo Merino Benítez', city: 'Santiago', country: 'Chili', continent: 'Amérique du Sud', timezone: 'America/Santiago', coordinates: { lat: -33.3930, lng: -70.7858 } },
  { code: 'UIO', name: 'Mariscal Sucre', city: 'Quito', country: 'Équateur', continent: 'Amérique du Sud', timezone: 'America/Guayaquil', coordinates: { lat: -0.1292, lng: -78.3575 } },
  { code: 'GYE', name: 'José Joaquín de Olmedo', city: 'Guayaquil', country: 'Équateur', continent: 'Amérique du Sud', timezone: 'America/Guayaquil', coordinates: { lat: -2.1574, lng: -79.8883 } },
  { code: 'GPS', name: 'Seymour', city: 'Îles Galápagos', country: 'Équateur', continent: 'Amérique du Sud', timezone: 'Pacific/Galapagos', coordinates: { lat: -0.4538, lng: -90.2659 } },
  { code: 'MVD', name: 'Carrasco', city: 'Montevideo', country: 'Uruguay', continent: 'Amérique du Sud', timezone: 'America/Montevideo', coordinates: { lat: -34.8384, lng: -56.0308 } },
  { code: 'ASU', name: 'Silvio Pettirossi', city: 'Asunción', country: 'Paraguay', continent: 'Amérique du Sud', timezone: 'America/Asuncion', coordinates: { lat: -25.2400, lng: -57.5197 } },
  { code: 'VVI', name: 'Viru Viru', city: 'Santa Cruz', country: 'Bolivie', continent: 'Amérique du Sud', timezone: 'America/La_Paz', coordinates: { lat: -17.6448, lng: -63.1354 } },
  { code: 'LPB', name: 'El Alto', city: 'La Paz', country: 'Bolivie', continent: 'Amérique du Sud', timezone: 'America/La_Paz', coordinates: { lat: -16.5133, lng: -68.1923 } },
  { code: 'CUZ', name: 'Alejandro Velasco Astete', city: 'Cusco', country: 'Pérou', continent: 'Amérique du Sud', timezone: 'America/Lima', coordinates: { lat: -13.5357, lng: -71.9388 } },
  { code: 'BSB', name: 'Presidente Juscelino Kubitschek', city: 'Brasília', country: 'Brésil', continent: 'Amérique du Sud', timezone: 'America/Sao_Paulo', coordinates: { lat: -15.8697, lng: -47.9208 } },
  { code: 'SSA', name: 'Deputado Luís Eduardo Magalhães', city: 'Salvador', country: 'Brésil', continent: 'Amérique du Sud', timezone: 'America/Bahia', coordinates: { lat: -12.9086, lng: -38.3225 } },
  { code: 'FOR', name: 'Pinto Martins', city: 'Fortaleza', country: 'Brésil', continent: 'Amérique du Sud', timezone: 'America/Fortaleza', coordinates: { lat: -3.7763, lng: -38.5326 } },
  { code: 'REC', name: 'Guararapes', city: 'Recife', country: 'Brésil', continent: 'Amérique du Sud', timezone: 'America/Recife', coordinates: { lat: -8.1263, lng: -34.9236 } },
  { code: 'MAO', name: 'Eduardo Gomes', city: 'Manaus', country: 'Brésil', continent: 'Amérique du Sud', timezone: 'America/Manaus', coordinates: { lat: -3.0386, lng: -60.0497 } },
  { code: 'BEL', name: 'Val de Cans', city: 'Belém', country: 'Brésil', continent: 'Amérique du Sud', timezone: 'America/Belem', coordinates: { lat: -1.3793, lng: -48.4763 } },
  { code: 'CNF', name: 'Tancredo Neves', city: 'Belo Horizonte', country: 'Brésil', continent: 'Amérique du Sud', timezone: 'America/Sao_Paulo', coordinates: { lat: -19.6244, lng: -43.9719 } },
  { code: 'POA', name: 'Salgado Filho', city: 'Porto Alegre', country: 'Brésil', continent: 'Amérique du Sud', timezone: 'America/Sao_Paulo', coordinates: { lat: -29.9944, lng: -51.1714 } },
  { code: 'CWB', name: 'Afonso Pena', city: 'Curitiba', country: 'Brésil', continent: 'Amérique du Sud', timezone: 'America/Sao_Paulo', coordinates: { lat: -25.5285, lng: -49.1758 } },
  { code: 'MDE', name: 'José María Córdova', city: 'Medellín', country: 'Colombie', continent: 'Amérique du Sud', timezone: 'America/Bogota', coordinates: { lat: 6.1644, lng: -75.4233 } },
  { code: 'CTG', name: 'Rafael Núñez', city: 'Carthagène', country: 'Colombie', continent: 'Amérique du Sud', timezone: 'America/Bogota', coordinates: { lat: 10.4424, lng: -75.5130 } },
  { code: 'CLO', name: 'Alfonso Bonilla Aragón', city: 'Cali', country: 'Colombie', continent: 'Amérique du Sud', timezone: 'America/Bogota', coordinates: { lat: 3.5432, lng: -76.3816 } },
  { code: 'COR', name: 'Ingeniero Taravella', city: 'Córdoba', country: 'Argentine', continent: 'Amérique du Sud', timezone: 'America/Argentina/Cordoba', coordinates: { lat: -31.3236, lng: -64.2080 } },
  { code: 'MDZ', name: 'El Plumerillo', city: 'Mendoza', country: 'Argentine', continent: 'Amérique du Sud', timezone: 'America/Argentina/Mendoza', coordinates: { lat: -32.8317, lng: -68.7929 } },
  { code: 'IGU', name: 'Cataratas', city: 'Foz do Iguaçu', country: 'Brésil', continent: 'Amérique du Sud', timezone: 'America/Sao_Paulo', coordinates: { lat: -25.5953, lng: -54.4872 } },
  { code: 'CCS', name: 'Simón Bolívar', city: 'Caracas', country: 'Venezuela', continent: 'Amérique du Sud', timezone: 'America/Caracas', coordinates: { lat: 10.6013, lng: -66.9912 } },
  { code: 'GEO', name: 'Cheddi Jagan', city: 'Georgetown', country: 'Guyana', continent: 'Amérique du Sud', timezone: 'America/Guyana', coordinates: { lat: 6.4986, lng: -58.2541 } },
  { code: 'PBM', name: 'Johan Adolf Pengel', city: 'Paramaribo', country: 'Suriname', continent: 'Amérique du Sud', timezone: 'America/Paramaribo', coordinates: { lat: 5.4528, lng: -55.1878 } },
  { code: 'CAY', name: 'Cayenne Félix Eboué', city: 'Cayenne', country: 'Guyane Française', continent: 'Amérique du Sud', timezone: 'America/Cayenne', coordinates: { lat: 4.8198, lng: -52.3604 } },

  // Afrique
  { code: 'CAI', name: 'Cairo', city: 'Le Caire', country: 'Égypte', continent: 'Afrique', timezone: 'Africa/Cairo', coordinates: { lat: 30.1219, lng: 31.4056 } },
  { code: 'RAK', name: 'Marrakech Menara', city: 'Marrakech', country: 'Maroc', continent: 'Afrique', timezone: 'Africa/Casablanca', coordinates: { lat: 31.6069, lng: -8.0363 } },
  { code: 'CMN', name: 'Mohammed V', city: 'Casablanca', country: 'Maroc', continent: 'Afrique', timezone: 'Africa/Casablanca', coordinates: { lat: 33.3675, lng: -7.5898 } },
  { code: 'TUN', name: 'Tunis-Carthage', city: 'Tunis', country: 'Tunisie', continent: 'Afrique', timezone: 'Africa/Tunis', coordinates: { lat: 36.8510, lng: 10.2272 } },
  { code: 'CPT', name: 'Cape Town', city: 'Le Cap', country: 'Afrique du Sud', continent: 'Afrique', timezone: 'Africa/Johannesburg', coordinates: { lat: -33.9715, lng: 18.6021 } },
  { code: 'JNB', name: 'O.R. Tambo', city: 'Johannesburg', country: 'Afrique du Sud', continent: 'Afrique', timezone: 'Africa/Johannesburg', coordinates: { lat: -26.1367, lng: 28.2411 } },
  { code: 'NBO', name: 'Jomo Kenyatta', city: 'Nairobi', country: 'Kenya', continent: 'Afrique', timezone: 'Africa/Nairobi', coordinates: { lat: -1.3192, lng: 36.9278 } },
  { code: 'MBA', name: 'Moi', city: 'Mombasa', country: 'Kenya', continent: 'Afrique', timezone: 'Africa/Nairobi', coordinates: { lat: -4.0348, lng: 39.5942 } },
  { code: 'ADD', name: 'Bole', city: 'Addis-Abeba', country: 'Éthiopie', continent: 'Afrique', timezone: 'Africa/Addis_Ababa', coordinates: { lat: 8.9779, lng: 38.7993 } },
  { code: 'LOS', name: 'Murtala Muhammed', city: 'Lagos', country: 'Nigeria', continent: 'Afrique', timezone: 'Africa/Lagos', coordinates: { lat: 6.5774, lng: 3.3212 } },
  { code: 'ABV', name: 'Nnamdi Azikiwe', city: 'Abuja', country: 'Nigeria', continent: 'Afrique', timezone: 'Africa/Lagos', coordinates: { lat: 9.0068, lng: 7.2632 } },
  { code: 'ACC', name: 'Kotoka', city: 'Accra', country: 'Ghana', continent: 'Afrique', timezone: 'Africa/Accra', coordinates: { lat: 5.6052, lng: -0.1668 } },
  { code: 'DKR', name: 'Blaise Diagne', city: 'Dakar', country: 'Sénégal', continent: 'Afrique', timezone: 'Africa/Dakar', coordinates: { lat: 14.6700, lng: -17.0733 } },
  { code: 'ABJ', name: 'Félix-Houphouët-Boigny', city: 'Abidjan', country: 'Côte d\'Ivoire', continent: 'Afrique', timezone: 'Africa/Abidjan', coordinates: { lat: 5.2614, lng: -3.9263 } },
  { code: 'ALG', name: 'Houari Boumediene', city: 'Alger', country: 'Algérie', continent: 'Afrique', timezone: 'Africa/Algiers', coordinates: { lat: 36.6910, lng: 3.2154 } },
  { code: 'FEZ', name: 'Fès-Saïss', city: 'Fès', country: 'Maroc', continent: 'Afrique', timezone: 'Africa/Casablanca', coordinates: { lat: 33.9273, lng: -4.9779 } },
  { code: 'TNG', name: 'Tanger Ibn Battouta', city: 'Tanger', country: 'Maroc', continent: 'Afrique', timezone: 'Africa/Casablanca', coordinates: { lat: 35.7269, lng: -5.9169 } },
  { code: 'AGA', name: 'Al Massira', city: 'Agadir', country: 'Maroc', continent: 'Afrique', timezone: 'Africa/Casablanca', coordinates: { lat: 30.3250, lng: -9.4131 } },
  { code: 'SSH', name: 'Sharm el-Sheikh', city: 'Sharm el-Sheikh', country: 'Égypte', continent: 'Afrique', timezone: 'Africa/Cairo', coordinates: { lat: 27.9773, lng: 34.3950 } },
  { code: 'HRG', name: 'Hurghada', city: 'Hurghada', country: 'Égypte', continent: 'Afrique', timezone: 'Africa/Cairo', coordinates: { lat: 27.1783, lng: 33.7994 } },
  { code: 'LXR', name: 'Luxor', city: 'Louxor', country: 'Égypte', continent: 'Afrique', timezone: 'Africa/Cairo', coordinates: { lat: 25.6710, lng: 32.7066 } },
  { code: 'ASW', name: 'Aswan', city: 'Assouan', country: 'Égypte', continent: 'Afrique', timezone: 'Africa/Cairo', coordinates: { lat: 23.9644, lng: 32.8200 } },
  { code: 'DJE', name: 'Djerba-Zarzis', city: 'Djerba', country: 'Tunisie', continent: 'Afrique', timezone: 'Africa/Tunis', coordinates: { lat: 33.8750, lng: 10.7755 } },
  { code: 'MIR', name: 'Monastir Habib Bourguiba', city: 'Monastir', country: 'Tunisie', continent: 'Afrique', timezone: 'Africa/Tunis', coordinates: { lat: 35.7581, lng: 10.7547 } },
  { code: 'DUR', name: 'King Shaka', city: 'Durban', country: 'Afrique du Sud', continent: 'Afrique', timezone: 'Africa/Johannesburg', coordinates: { lat: -29.6144, lng: 31.1197 } },
  { code: 'PLZ', name: 'Port Elizabeth', city: 'Port Elizabeth', country: 'Afrique du Sud', continent: 'Afrique', timezone: 'Africa/Johannesburg', coordinates: { lat: -33.9849, lng: 25.6173 } },
  { code: 'HLA', name: 'Lanseria', city: 'Johannesburg', country: 'Afrique du Sud', continent: 'Afrique', timezone: 'Africa/Johannesburg', coordinates: { lat: -25.9385, lng: 27.9261 } },
  { code: 'WDH', name: 'Hosea Kutako', city: 'Windhoek', country: 'Namibie', continent: 'Afrique', timezone: 'Africa/Windhoek', coordinates: { lat: -22.4799, lng: 17.4709 } },
  { code: 'LVI', name: 'Livingstone', city: 'Livingstone', country: 'Zambie', continent: 'Afrique', timezone: 'Africa/Lusaka', coordinates: { lat: -17.8218, lng: 25.8227 } },
  { code: 'LUN', name: 'Kenneth Kaunda', city: 'Lusaka', country: 'Zambie', continent: 'Afrique', timezone: 'Africa/Lusaka', coordinates: { lat: -15.3308, lng: 28.4524 } },
  { code: 'HRE', name: 'Robert Gabriel Mugabe', city: 'Harare', country: 'Zimbabwe', continent: 'Afrique', timezone: 'Africa/Harare', coordinates: { lat: -17.9318, lng: 31.0928 } },
  { code: 'VFA', name: 'Victoria Falls', city: 'Victoria Falls', country: 'Zimbabwe', continent: 'Afrique', timezone: 'Africa/Harare', coordinates: { lat: -18.0959, lng: 25.8390 } },
  { code: 'MRU', name: 'Roberts', city: 'Monrovia', country: 'Liberia', continent: 'Afrique', timezone: 'Africa/Monrovia', coordinates: { lat: 6.2337, lng: -10.3623 } },
  { code: 'FNA', name: 'Freetown', city: 'Freetown', country: 'Sierra Leone', continent: 'Afrique', timezone: 'Africa/Freetown', coordinates: { lat: 8.6164, lng: -13.1956 } },
  { code: 'BJL', name: 'Banjul', city: 'Banjul', country: 'Gambie', continent: 'Afrique', timezone: 'Africa/Banjul', coordinates: { lat: 13.3380, lng: -16.6522 } },
  { code: 'DSS', name: 'Blaise Diagne', city: 'Diass', country: 'Sénégal', continent: 'Afrique', timezone: 'Africa/Dakar', coordinates: { lat: 14.6700, lng: -17.0733 } },
  { code: 'ZNZ', name: 'Abeid Amani Karume', city: 'Zanzibar', country: 'Tanzanie', continent: 'Afrique', timezone: 'Africa/Dar_es_Salaam', coordinates: { lat: -6.2220, lng: 39.2249 } },
  { code: 'DAR', name: 'Julius Nyerere', city: 'Dar es Salaam', country: 'Tanzanie', continent: 'Afrique', timezone: 'Africa/Dar_es_Salaam', coordinates: { lat: -6.8781, lng: 39.2026 } },
  { code: 'JRO', name: 'Kilimanjaro', city: 'Arusha', country: 'Tanzanie', continent: 'Afrique', timezone: 'Africa/Dar_es_Salaam', coordinates: { lat: -3.4294, lng: 37.0745 } },
  { code: 'EBB', name: 'Entebbe', city: 'Entebbe', country: 'Ouganda', continent: 'Afrique', timezone: 'Africa/Kampala', coordinates: { lat: 0.0424, lng: 32.4435 } },
  { code: 'KGL', name: 'Kigali', city: 'Kigali', country: 'Rwanda', continent: 'Afrique', timezone: 'Africa/Kigali', coordinates: { lat: -1.9686, lng: 30.1395 } },
  { code: 'TNR', name: 'Ivato', city: 'Antananarivo', country: 'Madagascar', continent: 'Afrique', timezone: 'Indian/Antananarivo', coordinates: { lat: -18.7969, lng: 47.4788 } },
  { code: 'NOS', name: 'Fascene', city: 'Nosy Be', country: 'Madagascar', continent: 'Afrique', timezone: 'Indian/Antananarivo', coordinates: { lat: -13.3121, lng: 48.3148 } },
  // Océanie
  { code: 'SYD', name: 'Sydney Kingsford Smith', city: 'Sydney', country: 'Australie', continent: 'Océanie', timezone: 'Australia/Sydney', coordinates: { lat: -33.9399, lng: 151.1753 } },
  { code: 'MEL', name: 'Melbourne', city: 'Melbourne', country: 'Australie', continent: 'Océanie', timezone: 'Australia/Melbourne', coordinates: { lat: -37.6690, lng: 144.8410 } },
  { code: 'BNE', name: 'Brisbane', city: 'Brisbane', country: 'Australie', continent: 'Océanie', timezone: 'Australia/Brisbane', coordinates: { lat: -27.3942, lng: 153.1218 } },
  { code: 'AKL', name: 'Auckland', city: 'Auckland', country: 'Nouvelle-Zélande', continent: 'Océanie', timezone: 'Pacific/Auckland', coordinates: { lat: -37.0082, lng: 174.7850 } },
  { code: 'PPT', name: 'Tahiti Faa\'a', city: 'Papeete', country: 'Polynésie Française', continent: 'Océanie', timezone: 'Pacific/Tahiti', coordinates: { lat: -17.5536, lng: -149.6061 } },
  { code: 'PER', name: 'Perth', city: 'Perth', country: 'Australie', continent: 'Océanie', timezone: 'Australia/Perth', coordinates: { lat: -31.9403, lng: 115.9672 } },
  { code: 'ADL', name: 'Adelaide', city: 'Adélaïde', country: 'Australie', continent: 'Océanie', timezone: 'Australia/Adelaide', coordinates: { lat: -34.9450, lng: 138.5311 } },
  { code: 'CNS', name: 'Cairns', city: 'Cairns', country: 'Australie', continent: 'Océanie', timezone: 'Australia/Brisbane', coordinates: { lat: -16.8736, lng: 145.7550 } },
  { code: 'DRW', name: 'Darwin', city: 'Darwin', country: 'Australie', continent: 'Océanie', timezone: 'Australia/Darwin', coordinates: { lat: -12.4147, lng: 130.8767 } },
  { code: 'HBA', name: 'Hobart', city: 'Hobart', country: 'Australie', continent: 'Océanie', timezone: 'Australia/Hobart', coordinates: { lat: -42.8361, lng: 147.5100 } },
  { code: 'OOL', name: 'Gold Coast', city: 'Gold Coast', country: 'Australie', continent: 'Océanie', timezone: 'Australia/Brisbane', coordinates: { lat: -28.1644, lng: 153.5050 } },
  { code: 'CBR', name: 'Canberra', city: 'Canberra', country: 'Australie', continent: 'Océanie', timezone: 'Australia/Sydney', coordinates: { lat: -35.3069, lng: 149.1950 } },
  { code: 'ASP', name: 'Alice Springs', city: 'Alice Springs', country: 'Australie', continent: 'Océanie', timezone: 'Australia/Darwin', coordinates: { lat: -23.8067, lng: 133.9022 } },
  { code: 'WLG', name: 'Wellington', city: 'Wellington', country: 'Nouvelle-Zélande', continent: 'Océanie', timezone: 'Pacific/Auckland', coordinates: { lat: -41.3272, lng: 174.8050 } },
  { code: 'CHC', name: 'Christchurch', city: 'Christchurch', country: 'Nouvelle-Zélande', continent: 'Océanie', timezone: 'Pacific/Auckland', coordinates: { lat: -43.4894, lng: 172.5319 } },
  { code: 'ZQN', name: 'Queenstown', city: 'Queenstown', country: 'Nouvelle-Zélande', continent: 'Océanie', timezone: 'Pacific/Auckland', coordinates: { lat: -45.0211, lng: 168.7392 } },
  { code: 'NAN', name: 'Nadi', city: 'Nadi', country: 'Fidji', continent: 'Océanie', timezone: 'Pacific/Fiji', coordinates: { lat: -17.7554, lng: 177.4433 } },
  { code: 'SUV', name: 'Nausori', city: 'Suva', country: 'Fidji', continent: 'Océanie', timezone: 'Pacific/Fiji', coordinates: { lat: -18.0434, lng: 178.5592 } },
  { code: 'NOU', name: 'La Tontouta', city: 'Nouméa', country: 'Nouvelle-Calédonie', continent: 'Océanie', timezone: 'Pacific/Noumea', coordinates: { lat: -22.0146, lng: 166.2130 } },
  { code: 'BOB', name: 'Motu-Mute', city: 'Bora Bora', country: 'Polynésie Française', continent: 'Océanie', timezone: 'Pacific/Tahiti', coordinates: { lat: -16.4444, lng: -151.7511 } },
  { code: 'MOZ', name: 'Moorea', city: 'Moorea', country: 'Polynésie Française', continent: 'Océanie', timezone: 'Pacific/Tahiti', coordinates: { lat: -17.4900, lng: -149.7619 } },
  { code: 'APW', name: 'Apia', city: 'Apia', country: 'Samoa', continent: 'Océanie', timezone: 'Pacific/Apia', coordinates: { lat: -13.8300, lng: -172.0083 } },
  { code: 'TBU', name: 'Fua\'amotu', city: 'Nuku\'alofa', country: 'Tonga', continent: 'Océanie', timezone: 'Pacific/Tongatapu', coordinates: { lat: -21.2412, lng: -175.1497 } },
  { code: 'VLI', name: 'Bauerfield', city: 'Port-Vila', country: 'Vanuatu', continent: 'Océanie', timezone: 'Pacific/Efate', coordinates: { lat: -17.6993, lng: 168.3197 } },
  { code: 'RAR', name: 'Rarotonga', city: 'Avarua', country: 'Îles Cook', continent: 'Océanie', timezone: 'Pacific/Rarotonga', coordinates: { lat: -21.2027, lng: -159.8056 } },
  { code: 'POM', name: 'Jacksons', city: 'Port Moresby', country: 'Papouasie-Nouvelle-Guinée', continent: 'Océanie', timezone: 'Pacific/Port_Moresby', coordinates: { lat: -9.4434, lng: 147.2200 } },
  { code: 'GUM', name: 'Antonio B. Won Pat', city: 'Hagåtña', country: 'Guam', continent: 'Océanie', timezone: 'Pacific/Guam', coordinates: { lat: 13.4834, lng: 144.7960 } },
  { code: 'SPN', name: 'Saipan', city: 'Saipan', country: 'Îles Mariannes du Nord', continent: 'Océanie', timezone: 'Pacific/Saipan', coordinates: { lat: 15.1190, lng: 145.7294 } },
  { code: 'KWJ', name: 'Gwangju', city: 'Gwangju', country: 'Corée du Sud', continent: 'Asie', timezone: 'Asia/Seoul', coordinates: { lat: 35.1264, lng: 126.8086 } },
  { code: 'MAJ', name: 'Marshall Islands', city: 'Majuro', country: 'Îles Marshall', continent: 'Océanie', timezone: 'Pacific/Majuro', coordinates: { lat: 7.0647, lng: 171.2720 } },
  { code: 'PNI', name: 'Pohnpei', city: 'Pohnpei', country: 'Micronésie', continent: 'Océanie', timezone: 'Pacific/Pohnpei', coordinates: { lat: 6.9851, lng: 158.2089 } },
  { code: 'TRW', name: 'Bonriki', city: 'Tarawa', country: 'Kiribati', continent: 'Océanie', timezone: 'Pacific/Tarawa', coordinates: { lat: 1.3816, lng: 173.1470 } },

  // Destinations exotiques / Iles
  { code: 'MLE', name: 'Velana', city: 'Malé', country: 'Maldives', continent: 'Asie', timezone: 'Indian/Maldives', coordinates: { lat: 4.1917, lng: 73.5289 } },
  { code: 'SEZ', name: 'Seychelles', city: 'Mahé', country: 'Seychelles', continent: 'Afrique', timezone: 'Indian/Mahe', coordinates: { lat: -4.6740, lng: 55.5218 } },
  { code: 'MRU', name: 'Sir Seewoosagur Ramgoolam', city: 'Port Louis', country: 'Maurice', continent: 'Afrique', timezone: 'Indian/Mauritius', coordinates: { lat: -20.4302, lng: 57.6836 } },
  { code: 'REU', name: 'Roland Garros', city: 'Saint-Denis', country: 'La Réunion', continent: 'Afrique', timezone: 'Indian/Reunion', coordinates: { lat: -20.8871, lng: 55.5103 } },
  { code: 'PTP', name: 'Pointe-à-Pitre', city: 'Pointe-à-Pitre', country: 'Guadeloupe', continent: 'Amérique du Nord', timezone: 'America/Guadeloupe', coordinates: { lat: 16.2653, lng: -61.5318 } },
  { code: 'FDF', name: 'Martinique Aimé Césaire', city: 'Fort-de-France', country: 'Martinique', continent: 'Amérique du Nord', timezone: 'America/Martinique', coordinates: { lat: 14.5910, lng: -61.0032 } },
  { code: 'SFG', name: 'Grand Case', city: 'Grand Case', country: 'Saint-Martin', continent: 'Amérique du Nord', timezone: 'America/Marigot', coordinates: { lat: 18.0996, lng: -63.0472 } },
  { code: 'DZA', name: 'Dzaoudzi', city: 'Dzaoudzi', country: 'Mayotte', continent: 'Afrique', timezone: 'Indian/Mayotte', coordinates: { lat: -12.8047, lng: 45.2811 } },
  { code: 'IPC', name: 'Mataveri', city: 'Hanga Roa', country: 'Île de Pâques', continent: 'Amérique du Sud', timezone: 'Pacific/Easter', coordinates: { lat: -27.1648, lng: -109.4219 } },
  { code: 'TFN', name: 'Tenerife Norte', city: 'Tenerife', country: 'Espagne', continent: 'Europe', timezone: 'Atlantic/Canary', coordinates: { lat: 28.4827, lng: -16.3415 } },
  { code: 'FUE', name: 'Fuerteventura', city: 'Puerto del Rosario', country: 'Espagne', continent: 'Europe', timezone: 'Atlantic/Canary', coordinates: { lat: 28.4527, lng: -13.8638 } },
  { code: 'VXE', name: 'São Vicente', city: 'Mindelo', country: 'Cap-Vert', continent: 'Afrique', timezone: 'Atlantic/Cape_Verde', coordinates: { lat: 16.8332, lng: -25.0553 } },
  { code: 'SID', name: 'Amílcar Cabral', city: 'Sal', country: 'Cap-Vert', continent: 'Afrique', timezone: 'Atlantic/Cape_Verde', coordinates: { lat: 16.7414, lng: -22.9494 } },
  { code: 'RAI', name: 'Praia', city: 'Praia', country: 'Cap-Vert', continent: 'Afrique', timezone: 'Atlantic/Cape_Verde', coordinates: { lat: 14.9245, lng: -23.4935 } },
  { code: 'FNC', name: 'Cristiano Ronaldo', city: 'Funchal', country: 'Portugal', continent: 'Europe', timezone: 'Atlantic/Madeira', coordinates: { lat: 32.6979, lng: -16.7745 } },
  { code: 'PDL', name: 'João Paulo II', city: 'Ponta Delgada', country: 'Portugal', continent: 'Europe', timezone: 'Atlantic/Azores', coordinates: { lat: 37.7412, lng: -25.6979 } },
  { code: 'TER', name: 'Lajes', city: 'Terceira', country: 'Portugal', continent: 'Europe', timezone: 'Atlantic/Azores', coordinates: { lat: 38.7619, lng: -27.0908 } },
  { code: 'HOR', name: 'Horta', city: 'Horta', country: 'Portugal', continent: 'Europe', timezone: 'Atlantic/Azores', coordinates: { lat: 38.5199, lng: -28.7159 } },
]

// Fonction de recherche universelle
export function searchAirports(query: string, limit: number = 50): Airport[] {
  if (!query || query.trim().length < 2) {
    return []
  }

  const searchTerm = query.toLowerCase().trim()

  const results = AIRPORTS.filter(airport =>
    airport.city.toLowerCase().includes(searchTerm) ||
    airport.country.toLowerCase().includes(searchTerm) ||
    airport.code.toLowerCase().includes(searchTerm) ||
    airport.name.toLowerCase().includes(searchTerm)
  )

  return results.slice(0, limit)
}

// Obtenir un aéroport par code
export function getAirportByCode(code: string): Airport | undefined {
  return AIRPORTS.find(airport => airport.code === code)
}

// Obtenir image d'une destination (via Unsplash)
export function getDestinationImage(city: string): string {
  // Mapping spécifique pour les villes principales
  const cityImages: Record<string, string> = {
    'Paris': 'photo-1502602898657-3e91760cbb34',
    'Londres': 'photo-1513635269975-59663e0ac1ad',
    'New York': 'photo-1496442226666-8d4d0e62e6e9',
    'Tokyo': 'photo-1540959733332-eab4deabeeaf',
    'Dubai': 'photo-1512453979798-5ea266f8880c',
    'Bangkok': 'photo-1508009603885-50cf7c579365',
    'Singapour': 'photo-1525625293386-3f8f99389edd',
    'Sydney': 'photo-1506973035872-a4ec16b8e8d9',
    'Rome': 'photo-1552832230-c0197dd311b5',
    'Barcelone': 'photo-1583422409516-2895a77efded',
    'Amsterdam': 'photo-1534351590666-13e3e96b5017',
    'Istanbul': 'photo-1524231757912-21f4fe3a7200',
    'Bali': 'photo-1537996194471-e657df975ab4',
    'Rio de Janeiro': 'photo-1483729558449-99ef09a8c325',
    'Los Angeles': 'photo-1534190239940-9ba8944ea261',
    'Miami': 'photo-1533106418989-88406c7cc8ca',
  }

  const photoId = cityImages[city]
  if (photoId) {
    return `https://images.unsplash.com/${photoId}?w=800&auto=format&fit=crop&q=80`
  }

  // Image par défaut pour les autres destinations
  return `https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&auto=format&fit=crop&q=80`
}
